### ISSUE TITLE
It can debug multiple projects in one solution?

### ISSUE THREAD

**Issue by D1987** [pavel-agarkov/RemoteDebugLauncherExtension#1]
Hi, I follow this topic https://itnext.io/how-to-debug-asp-net-core-in-kubernetes-from-visual-studio-2019-1e9d16099d99.
It works with one project well, can it work with multiple projects, if yes what should I change in kube-debug.sh and launch.json?

**Comment by pavel-agarkov** [comment]
Yes it works with multiple projects.
You need to create launch.json for each project and put it inside its Properties folder.
We normally have different --selector, --container and --namespace flags for each launch.json

**Comment by D1987** [comment]
Thank you!
